"""Quellenverzeichnis. Einzige Stelle, an der URLs und Quellenbeschreibungen stehen.

Die Website zeigt dieses Verzeichnis (über site/data/sources.json) in der Quellenansicht.
"""

FA = "https://www.deutsche-finanzagentur.de/fileadmin/user_upload/Institutionelle-investoren"
G20 = ["ARG", "AUS", "BRA", "CAN", "CHN", "FRA", "DEU", "IND", "IDN", "ITA", "JPN", "KOR", "MEX", "RUS", "SAU", "ZAF", "TUR", "GBR", "USA"]
WB_COUNTRIES = ";".join(G20)

SOURCES = {
    "de_emissionshistorie": {
        "title": "Auktionsergebnisse seit 1999 (Emissionshistorie)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH / Deutsche Bundesbank",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/emissionen/emissionsergebnisse",
        "download": f"{FA}/auktionen/emissionshistorie_dt.xlsx",
        "file": "de/emissionshistorie_dt.xlsx",
        "used_for": "Jede einzelne Emission: Datum, ISIN, Kupon, Fälligkeit, zugeteiltes Volumen, "
                    "Marktpflegequote/Eigenbestand, gewogener Durchschnittskurs, Durchschnittsrendite. "
                    "Grundlage aller als „aus einzelnen Emissionen berechnet“ markierten Werte.",
    },
    "de_einzelaufstellung_jahre": {
        "title": "Ausstehende Bundeswertpapiere – Einzelaufstellung zu Jahresenden seit 1995",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/downloadcenter",
        "download": f"{FA}/berichtswesen/einzelaufstellung_jahre_dt.xlsx",
        "file": "de/einzelaufstellung_jahre_dt.xlsx",
        "used_for": "Zinslaufbeginn („Laufzeit ab“) je ISIN für Stückzinsen und ersten Kupon; "
                    "Abgleich der Emissionsvolumina mit dem Umlauf.",
    },
    "de_einzelaufstellung": {
        "title": "Ausstehende Bundeswertpapiere – aktuelle Einzelaufstellung",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/downloadcenter",
        "download": f"{FA}/berichtswesen/einzelaufstellung_dt.xlsx",
        "file": "de/einzelaufstellung_dt.xlsx",
        "used_for": "Zinslaufbeginn neuer Wertpapiere des laufenden Jahres.",
    },
    "de_schuldenbericht": {
        "title": "Schuldenbericht: Schuldenstand, Bruttokreditaufnahme, Tilgungen, Zinsen (monatlich seit 1995)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH, Abteilung F-HH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/finanzierung-des-bundes/schuldenstatistik/zinsen",
        "download": f"{FA}/berichtswesen/schuldenbericht_dt.xlsx",
        "file": "de/schuldenbericht_dt.xlsx",
        "used_for": "Tatsächlich im Jahr gezahlte Zinsen (Vergleichszahl), amtliche Bruttokreditaufnahme "
                    "und Tilgungen (Aufteilung Anschlussfinanzierung / Nettokreditaufnahme, Abdeckungsgrad).",
    },
    "de_referenzindex_2005": {
        "title": "Archiv täglicher Referenzindex und Index-Verhältniszahlen (Basisjahr 2005)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/bundeswertpapierarten/inflationsindexierte-bundeswertpapiere",
        "download": f"{FA}/indexverhaeltnis/archiv_referenzindex_bj2005_dt.xlsx",
        "file": "de/archiv_referenzindex_bj2005_dt.xlsx",
        "used_for": "Realisierte Index-Verhältniszahlen inflationsindexierter Bundeswertpapiere 2006–2016.",
    },
    "de_referenzindex_2015": {
        "title": "Archiv täglicher Referenzindex und Index-Verhältniszahlen (Basisjahr 2015)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/bundeswertpapierarten/inflationsindexierte-bundeswertpapiere",
        "download": f"{FA}/indexverhaeltnis/archiv_referenzindex_bj2015_dt.xlsx",
        "file": "de/archiv_referenzindex_bj2015_dt.xlsx",
        "used_for": "Realisierte Index-Verhältniszahlen ab 2016, Basisindizes, Zinslaufbeginn und erster Kupon "
                    "der inflationsindexierten Bundeswertpapiere; Ausgangspunkt der Inflationsprojektion.",
    },
    "de_referenzindex_2025": {
        "title": "Täglicher Referenzindex und Index-Verhältniszahlen (Basisjahr 2025)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/bundeswertpapierarten/inflationsindexierte-bundeswertpapiere",
        "download": f"{FA}/indexverhaeltnis/archiv_referenzindex_bj2025_dt.xlsx",
        "file": "de/archiv_referenzindex_bj2025_dt.xlsx",
        "used_for": "Aktuelle Index-Verhältniszahlen nach Umbasierung des HVPI auf 2025=100; letzter amtlicher "
                    "Wert ist Ausgangspunkt der Inflationsprojektion.",
    },
    "bbk_gross": {
        "title": "Brutto-Absatz von Anleihen des Bundes zu Nominalwerten (monatlich ab 1948)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.ABS.FV._T.S1311.A.A.A.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.ABS.FV._T.S1311.A.A.A.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.ABS.FV._T.S1311.A.A.A.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_gross.csv",
        "used_for": "Brutto-Kreditaufnahme über Bundesanleihen vor 1999 (amtlich, aggregiert); Nettoabsatz aus Umlaufänderung. Ab 2000 einschließlich Bubills und Finanzierungsschätze.",
    },
    "bbk_gross_le4": {
        "title": "Brutto-Absatz von Anleihen des Bundes, vereinbarte Laufzeit bis 4 Jahre (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.ABS.FV._T.S1311.A.A.VB004.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.ABS.FV._T.S1311.A.A.VB004.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.ABS.FV._T.S1311.A.A.VB004.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_gross_le4.csv",
        "used_for": "Modell der Zinslast 1960–1998: Volumen mit kurzer Laufzeit.",
    },
    "bbk_gross_gt4": {
        "title": "Brutto-Absatz von Anleihen des Bundes, vereinbarte Laufzeit über 4 Jahre (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.ABS.FV._T.S1311.A.A.VG004.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.ABS.FV._T.S1311.A.A.VG004.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.ABS.FV._T.S1311.A.A.VG004.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_gross_gt4.csv",
        "used_for": "Modell der Zinslast 1960–1998: Volumen mit langer Laufzeit.",
    },
    "bbk_em_yield": {
        "title": "Emissionsrenditen börsennotierter Bundeswertpapiere (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.EMR.RD.EUR.S1311.A.A604.A.R.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.EMR.RD.EUR.S1311.A.A604.A.R.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.EMR.RD.EUR.S1311.A.A604.A.R.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_em_yield.csv",
        "used_for": "Modell der Zinslast 1960–1998: Rendite der im Monat begebenen Bundeswertpapiere.",
    },
    "bbk_outstanding": {
        "title": "Umlauf von Anleihen des Bundes zu Nominalwerten (monatlich ab 1948)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.UML.FV._T.S1311.A.A.A.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.UML.FV._T.S1311.A.A.A.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.UML.FV._T.S1311.A.A.A.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_outstanding.csv",
        "used_for": "Nettoabsatz = Umlaufänderung; Anschlussfinanzierung = Brutto-Absatz − Nettoabsatz (vor 1995).",
    },
    "bbk_umlaufrendite": {
        "title": "Umlaufsrendite börsennotierter Bundeswertpapiere (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.UMR.RD.EUR.S1311.B.A604.A.R.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.UMR.RD.EUR.S1311.B.A604.A.R.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.UMR.RD.EUR.S1311.B.A604.A.R.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_umlaufrendite.csv",
        "used_for": "Modell 1960–1998: Ersatzrendite für Monate, in denen Volumen begeben, aber keine Emissionsrendite veröffentlicht wurde.",
    },
    "us_auctions": {
        "title": "Treasury Securities Auctions Data (alle Auktionen seit 1979)",
        "publisher": "U.S. Department of the Treasury, Bureau of the Fiscal Service (FiscalData)",
        "kind": "amtlich",
        "country": "US",
        "landing": "https://fiscaldata.treasury.gov/datasets/treasury-securities-auctions-data/",
        "download": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/auctions_query?fields=cusip,security_type,security_term,auction_date,issue_date,maturity_date,dated_date,first_int_payment_date,first_int_period,int_payment_frequency,int_rate,price_per100,accrued_int_per100,adj_price,high_yield,high_discnt_rate,high_investment_rate,high_discnt_margin,spread,floating_rate,inflation_index_security,index_ratio_on_issue_date,ref_cpi_on_issue_date,ref_cpi_on_dated_date,total_accepted,comp_accepted,noncomp_accepted,soma_accepted,offering_amt,reopening,original_issue_date,cash_management_bill_cmb,series&page[size]=10000&sort=auction_date",
        "pages": 2,
        "file": "us/fiscaldata_auctions.json",
        "used_for": "Jede einzelne Auktion von Bills, Notes, Bonds, TIPS und FRN: Kurs, Stückzinsen, Kupon, Laufzeit, "
                    "zugeteiltes Volumen. Grundlage der US-Jahrgangskosten.",
    },
    "us_interest_expense": {
        "title": "Interest Expense on the Public Debt Outstanding (monatlich ab Mai 2010)",
        "publisher": "U.S. Department of the Treasury, Bureau of the Fiscal Service (FiscalData)",
        "kind": "amtlich",
        "country": "US",
        "landing": "https://fiscaldata.treasury.gov/datasets/interest-expense-debt-outstanding/",
        "download": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/interest_expense?page[size]=10000&sort=record_date",
        "pages": 1,
        "file": "us/fiscaldata_interest_expense.json",
        "used_for": "Tatsächlich gezahlte bzw. aufgelaufene Zinsen auf die Bundesschuld je Kalenderjahr (Vergleichszahl, ab 2011 vollständig).",
    },
    "bbk_vgr_interest": {
        "title": "Zinsausgaben des Staates (Gesamtstaat, VGR/ESVG 2010), jährlich ab 1970",
        "publisher": "Deutsche Bundesbank / Statistisches Bundesamt (Zeitreihe BBGFS1.A.BJ9182)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBGFS1.A.BJ9182",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBGFS1/A.BJ9182?format=csv",
        "file": "de/bundesbank_vgr_zinsausgaben_staat.csv",
        "used_for": "Gesamtstaat-Ansicht: Zinsausgaben von Bund, Ländern, Gemeinden und Sozialversicherung (periodengerecht, VGR).",
    },
    "us_tips_refcpi": {
        "title": "TIPS: tägliche Referenz-CPI-Werte (ab Mai 2008)",
        "publisher": "U.S. Department of the Treasury, Bureau of the Fiscal Service (FiscalData, TIPS CPI Data)",
        "kind": "amtlich",
        "country": "US",
        "landing": "https://fiscaldata.treasury.gov/datasets/tips-cpi-data/",
        "download": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/tips_cpi_data_detail?filter=cusip:eq:912810FD5&fields=index_date,ref_cpi&page[size]=10000&sort=index_date",
        "pages": 1,
        "file": "us/fiscaldata_tips_refcpi.json",
        "used_for": "Index-Verhältniszahlen der TIPS (Referenz-CPI / Referenz-CPI am Zinslaufbeginn). Vor Mai 2008: Interpolation "
                    "zwischen den amtlichen Referenz-CPI-Werten der Emissionstage (modelliert).",
    },
    "wb_interest": {
        "title": "World Development Indicators: Interest payments (current LCU), GC.XPN.INTP.CN",
        "publisher": "Weltbank (Datenbasis: IWF Government Finance Statistics)",
        "kind": "international",
        "country": None,
        "landing": "https://data.worldbank.org/indicator/GC.XPN.INTP.CN",
        "download": f"https://api.worldbank.org/v2/country/{WB_COUNTRIES}/indicator/GC.XPN.INTP.CN?format=json&per_page=2000&date=1960:2030",
        "file": "intl/worldbank_GC.XPN.INTP.CN.json",
        "used_for": "Gezahlte Zinsen des Zentralstaats in Landeswährung als Vergleichszahl für Jahre und Länder "
                    "ohne amtliche Einzeldaten. Nicht für Jahrgangskosten verwendbar.",
    },
    "imf_weo": {
        "title": "World Economic Outlook: Finanzierungssaldo, Primärsaldo und Bruttoschulden des Gesamtstaats (% des BIP)",
        "publisher": "Internationaler Währungsfonds (IWF), SDMX-Schnittstelle, Datensatz IMF.RES:WEO",
        "kind": "international",
        "country": None,
        "landing": "https://www.imf.org/en/Publications/WEO",
        "download": "https://api.imf.org/external/sdmx/2.1/data/IMF.RES,WEO,9.0.0/" + "+".join(G20)
                    + ".GGXCNL_NGDP+GGXONLB_NGDP+GGXWDG_NGDP.A?format=csv",
        "accept": "application/vnd.sdmx.data+csv;version=1.0.0",
        "file": "intl/imf_weo_g20.csv",
        "used_for": "Gesamtstaat (alle Ebenen): Nettozinsausgaben = Primärsaldo − Finanzierungssaldo (in % des BIP, abgeleitet) "
                    "und Schuldenstand. Werte nach dem letzten Ist-Jahr sind IWF-Projektionen. Nicht für Jahrgangskosten verwendbar.",
    },
}

# Amtliche Quellen für Einzelemissionen weiterer Länder: erfasst, aber (noch) nicht importiert.
# "check" dokumentiert den Stand der automatischen Abrufprüfung aus dieser Arbeitsumgebung.
CANDIDATES = [
    {"country": "GB", "title": "UK Debt Management Office – Gilt Issuance History (Bericht D2.1E) und Gilts in Issue (D1A)",
     "url": "https://www.dmo.gov.uk/data/gilt-market/", "check": "maschinenlesbar abrufbar (XML, Emissionen seit 1981)",
     "note": "Fälligkeitstermine getilgter Gilts und RPI-Indexverhältnisse der inflationsindexierten Gilts fehlen noch; Import vorbereitet."},
    {"country": "CA", "title": "Bank of Canada – Government of Canada bond and bill auction results",
     "url": "https://www.bankofcanada.ca/markets/government-securities-auctions/", "check": "Valet-API erreichbar, Auktionsreihen nicht geprüft",
     "note": "Import nicht umgesetzt."},
    {"country": "FR", "title": "Agence France Trésor – Résultats des adjudications",
     "url": "https://www.aft.gouv.fr/fr/resultats-adjudications", "check": "automatischer Abruf blockiert (HTTP 403)",
     "note": "Einzelauktionen OAT/BTF; Import nicht umgesetzt."},
    {"country": "IT", "title": "Dipartimento del Tesoro – Risultati delle aste",
     "url": "https://www.dt.mef.gov.it/it/debito_pubblico/emissioni_titoli_di_stato_interni/", "check": "automatischer Abruf blockiert (HTTP 403)",
     "note": "Einzelauktionen BTP/BOT/CCTeu (variabel verzinst); Import nicht umgesetzt."},
    {"country": "AU", "title": "Australian Office of Financial Management – Tender results",
     "url": "https://www.aofm.gov.au/", "check": "automatischer Abruf blockiert (HTTP 403)", "note": "Import nicht umgesetzt."},
    {"country": "JP", "title": "Ministry of Finance Japan – JGB auction results",
     "url": "https://www.mof.go.jp/english/policy/jgbs/auction/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "IN", "title": "Reserve Bank of India – Auction results of government securities",
     "url": "https://www.rbi.org.in/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "BR", "title": "Tesouro Nacional – Resultados dos leilões",
     "url": "https://www.tesourotransparente.gov.br/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "MX", "title": "Banco de México – Subastas de valores gubernamentales",
     "url": "https://www.banxico.org.mx/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "KR", "title": "Ministry of Economy and Finance – KTB auction results",
     "url": "https://ktb.moef.go.kr/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "ZA", "title": "National Treasury – Government bond auction results",
     "url": "https://www.treasury.gov.za/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "TR", "title": "Hazine ve Maliye Bakanlığı – İhale sonuçları",
     "url": "https://www.hmb.gov.tr/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "ID", "title": "Kementerian Keuangan (DJPPR) – Hasil lelang SBN",
     "url": "https://www.djppr.kemenkeu.go.id/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "CN", "title": "Ministry of Finance / ChinaBond – Treasury bond issuance",
     "url": "https://www.chinabond.com.cn/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "AR", "title": "Ministerio de Economía – Licitaciones de títulos públicos",
     "url": "https://www.argentina.gob.ar/economia/finanzas", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "RU", "title": "Ministry of Finance of Russia – OFZ auction results",
     "url": "https://minfin.gov.ru/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "SA", "title": "National Debt Management Center – Sukuk issuance",
     "url": "https://www.ndmc.gov.sa/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
]
