"""Quellenverzeichnis. Einzige Stelle, an der URLs und Quellenbeschreibungen stehen.

Die Website zeigt dieses Verzeichnis (über site/data/sources.json) in der Quellenansicht.
"""

FA = "https://www.deutsche-finanzagentur.de/fileadmin/user_upload/Institutionelle-investoren"
G20 = ["ARG", "AUS", "BRA", "CAN", "CHN", "FRA", "DEU", "IND", "IDN", "ITA", "JPN", "KOR", "MEX", "RUS", "SAU", "ZAF", "TUR", "GBR", "USA"]
WB_COUNTRIES = ";".join(G20)

SOURCES = {
    "de_emissionshistorie": {
        "title": "Auktionsergebnisse seit 1999 (Emissionshistorie)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH / Deutsche Bundesbank",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/emissionen/emissionsergebnisse",
        "download": f"{FA}/auktionen/emissionshistorie_dt.xlsx",
        "file": "de/emissionshistorie_dt.xlsx",
        "used_for": "Jede einzelne Emission: Datum, ISIN, Kupon, Fälligkeit, zugeteiltes Volumen, "
                    "Marktpflegequote/Eigenbestand, gewogener Durchschnittskurs, Durchschnittsrendite. "
                    "Grundlage aller als „aus einzelnen Emissionen berechnet“ markierten Werte.",
    },
    "de_einzelaufstellung_jahre": {
        "title": "Ausstehende Bundeswertpapiere – Einzelaufstellung zu Jahresenden seit 1995",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/downloadcenter",
        "download": f"{FA}/berichtswesen/einzelaufstellung_jahre_dt.xlsx",
        "file": "de/einzelaufstellung_jahre_dt.xlsx",
        "used_for": "Zinslaufbeginn („Laufzeit ab“) je ISIN für Stückzinsen und ersten Kupon; "
                    "Abgleich der Emissionsvolumina mit dem Umlauf.",
    },
    "de_einzelaufstellung": {
        "title": "Ausstehende Bundeswertpapiere – aktuelle Einzelaufstellung",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/downloadcenter",
        "download": f"{FA}/berichtswesen/einzelaufstellung_dt.xlsx",
        "file": "de/einzelaufstellung_dt.xlsx",
        "used_for": "Zinslaufbeginn neuer Wertpapiere des laufenden Jahres.",
    },
    "de_schuldenbericht": {
        "title": "Schuldenbericht: Schuldenstand, Bruttokreditaufnahme, Tilgungen, Zinsen (monatlich seit 1995)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH, Abteilung F-HH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/finanzierung-des-bundes/schuldenstatistik/zinsen",
        "download": f"{FA}/berichtswesen/schuldenbericht_dt.xlsx",
        "file": "de/schuldenbericht_dt.xlsx",
        "used_for": "Tatsächlich im Jahr gezahlte Zinsen (Vergleichszahl), amtliche Bruttokreditaufnahme "
                    "und Tilgungen (Aufteilung Anschlussfinanzierung / Nettokreditaufnahme, Abdeckungsgrad).",
    },
    "de_referenzindex_2005": {
        "title": "Archiv täglicher Referenzindex und Index-Verhältniszahlen (Basisjahr 2005)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/bundeswertpapierarten/inflationsindexierte-bundeswertpapiere",
        "download": f"{FA}/indexverhaeltnis/archiv_referenzindex_bj2005_dt.xlsx",
        "file": "de/archiv_referenzindex_bj2005_dt.xlsx",
        "used_for": "Realisierte Index-Verhältniszahlen inflationsindexierter Bundeswertpapiere 2006–2016.",
    },
    "de_referenzindex_2015": {
        "title": "Archiv täglicher Referenzindex und Index-Verhältniszahlen (Basisjahr 2015)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/bundeswertpapierarten/inflationsindexierte-bundeswertpapiere",
        "download": f"{FA}/indexverhaeltnis/archiv_referenzindex_bj2015_dt.xlsx",
        "file": "de/archiv_referenzindex_bj2015_dt.xlsx",
        "used_for": "Realisierte Index-Verhältniszahlen ab 2016, Basisindizes, Zinslaufbeginn und erster Kupon "
                    "der inflationsindexierten Bundeswertpapiere; Ausgangspunkt der Inflationsprojektion.",
    },
    "de_referenzindex_2025": {
        "title": "Täglicher Referenzindex und Index-Verhältniszahlen (Basisjahr 2025)",
        "publisher": "Bundesrepublik Deutschland – Finanzagentur GmbH",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.deutsche-finanzagentur.de/bundeswertpapiere/bundeswertpapierarten/inflationsindexierte-bundeswertpapiere",
        "download": f"{FA}/indexverhaeltnis/archiv_referenzindex_bj2025_dt.xlsx",
        "file": "de/archiv_referenzindex_bj2025_dt.xlsx",
        "used_for": "Aktuelle Index-Verhältniszahlen nach Umbasierung des HVPI auf 2025=100; letzter amtlicher "
                    "Wert ist Ausgangspunkt der Inflationsprojektion.",
    },
    "bbk_gross": {
        "title": "Brutto-Absatz von Anleihen des Bundes zu Nominalwerten (monatlich ab 1948)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.ABS.FV._T.S1311.A.A.A.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.ABS.FV._T.S1311.A.A.A.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.ABS.FV._T.S1311.A.A.A.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_gross.csv",
        "used_for": "Brutto-Kreditaufnahme über Bundesanleihen vor 1999 (amtlich, aggregiert); Nettoabsatz aus Umlaufänderung. Ab 2000 einschließlich Bubills und Finanzierungsschätze.",
    },
    "bbk_gross_le4": {
        "title": "Brutto-Absatz von Anleihen des Bundes, vereinbarte Laufzeit bis 4 Jahre (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.ABS.FV._T.S1311.A.A.VB004.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.ABS.FV._T.S1311.A.A.VB004.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.ABS.FV._T.S1311.A.A.VB004.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_gross_le4.csv",
        "used_for": "Modell der Zinslast 1960–1998: Volumen mit kurzer Laufzeit.",
    },
    "bbk_gross_gt4": {
        "title": "Brutto-Absatz von Anleihen des Bundes, vereinbarte Laufzeit über 4 Jahre (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.ABS.FV._T.S1311.A.A.VG004.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.ABS.FV._T.S1311.A.A.VG004.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.ABS.FV._T.S1311.A.A.VG004.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_gross_gt4.csv",
        "used_for": "Modell der Zinslast 1960–1998: Volumen mit langer Laufzeit.",
    },
    "bbk_em_yield": {
        "title": "Emissionsrenditen börsennotierter Bundeswertpapiere (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.EMR.RD.EUR.S1311.A.A604.A.R.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.EMR.RD.EUR.S1311.A.A604.A.R.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.EMR.RD.EUR.S1311.A.A604.A.R.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_em_yield.csv",
        "used_for": "Modell der Zinslast 1960–1998: Rendite der im Monat begebenen Bundeswertpapiere.",
    },
    "bbk_outstanding": {
        "title": "Umlauf von Anleihen des Bundes zu Nominalwerten (monatlich ab 1948)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.UML.FV._T.S1311.A.A.A.A.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.UML.FV._T.S1311.A.A.A.A.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.UML.FV._T.S1311.A.A.A.A.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_outstanding.csv",
        "used_for": "Nettoabsatz = Umlaufänderung; Anschlussfinanzierung = Brutto-Absatz − Nettoabsatz (vor 1995).",
    },
    "bbk_umlaufrendite": {
        "title": "Umlaufsrendite börsennotierter Bundeswertpapiere (monatlich ab 1960)",
        "publisher": "Deutsche Bundesbank, Kapitalmarktstatistik (Zeitreihe BBSIS.M.I.UMR.RD.EUR.S1311.B.A604.A.R.A.A._Z._Z.A)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBSIS.M.I.UMR.RD.EUR.S1311.B.A604.A.R.A.A._Z._Z.A",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBSIS/M.I.UMR.RD.EUR.S1311.B.A604.A.R.A.A._Z._Z.A?format=csv",
        "file": "de/bundesbank_umlaufrendite.csv",
        "used_for": "Modell 1960–1998: Ersatzrendite für Monate, in denen Volumen begeben, aber keine Emissionsrendite veröffentlicht wurde.",
    },
    "us_auctions": {
        "title": "Treasury Securities Auctions Data (alle Auktionen seit 1979)",
        "publisher": "U.S. Department of the Treasury, Bureau of the Fiscal Service (FiscalData)",
        "kind": "amtlich",
        "country": "US",
        "landing": "https://fiscaldata.treasury.gov/datasets/treasury-securities-auctions-data/",
        "download": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/auctions_query?fields=cusip,security_type,security_term,auction_date,issue_date,maturity_date,dated_date,first_int_payment_date,first_int_period,int_payment_frequency,int_rate,price_per100,accrued_int_per100,adj_price,high_yield,high_discnt_rate,high_investment_rate,high_discnt_margin,spread,floating_rate,inflation_index_security,index_ratio_on_issue_date,ref_cpi_on_issue_date,ref_cpi_on_dated_date,total_accepted,comp_accepted,noncomp_accepted,soma_accepted,offering_amt,reopening,original_issue_date,cash_management_bill_cmb,series&page[size]=10000&sort=auction_date",
        "pages": 2,
        "file": "us/fiscaldata_auctions.json",
        "used_for": "Jede einzelne Auktion von Bills, Notes, Bonds, TIPS und FRN: Kurs, Stückzinsen, Kupon, Laufzeit, "
                    "zugeteiltes Volumen. Grundlage der US-Jahrgangskosten.",
    },
    "us_interest_expense": {
        "title": "Interest Expense on the Public Debt Outstanding (monatlich ab Mai 2010)",
        "publisher": "U.S. Department of the Treasury, Bureau of the Fiscal Service (FiscalData)",
        "kind": "amtlich",
        "country": "US",
        "landing": "https://fiscaldata.treasury.gov/datasets/interest-expense-debt-outstanding/",
        "download": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/interest_expense?page[size]=10000&sort=record_date",
        "pages": 1,
        "file": "us/fiscaldata_interest_expense.json",
        "used_for": "Tatsächlich gezahlte bzw. aufgelaufene Zinsen auf die Bundesschuld je Kalenderjahr (Vergleichszahl, ab 2011 vollständig).",
    },
    "bbk_vgr_interest": {
        "title": "Zinsausgaben des Staates (Gesamtstaat, VGR/ESVG 2010), jährlich ab 1970",
        "publisher": "Deutsche Bundesbank / Statistisches Bundesamt (Zeitreihe BBGFS1.A.BJ9182)",
        "kind": "amtlich",
        "country": "DE",
        "landing": "https://www.bundesbank.de/dynamic/action/de/statistiken/zeitreihen-datenbanken/zeitreihen-datenbank/723452/723452?tsId=BBGFS1.A.BJ9182",
        "download": "https://api.statistiken.bundesbank.de/rest/data/BBGFS1/A.BJ9182?format=csv",
        "file": "de/bundesbank_vgr_zinsausgaben_staat.csv",
        "used_for": "Gesamtstaat-Ansicht: Zinsausgaben von Bund, Ländern, Gemeinden und Sozialversicherung (periodengerecht, VGR).",
    },
    "us_tips_refcpi": {
        "title": "TIPS: tägliche Referenz-CPI-Werte (ab Mai 2008)",
        "publisher": "U.S. Department of the Treasury, Bureau of the Fiscal Service (FiscalData, TIPS CPI Data)",
        "kind": "amtlich",
        "country": "US",
        "landing": "https://fiscaldata.treasury.gov/datasets/tips-cpi-data/",
        "download": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/tips_cpi_data_detail?filter=cusip:eq:912810FD5&fields=index_date,ref_cpi&page[size]=10000&sort=index_date",
        "pages": 1,
        "file": "us/fiscaldata_tips_refcpi.json",
        "used_for": "Index-Verhältniszahlen der TIPS (Referenz-CPI / Referenz-CPI am Zinslaufbeginn). Vor Mai 2008: Interpolation "
                    "zwischen den amtlichen Referenz-CPI-Werten der Emissionstage (modelliert).",
    },
    "gb_auctions": {
        "title": "Results of Outright Gilt Auctions (ab 1998, einschließlich PAOF)",
        "publisher": "UK Debt Management Office (DMO), Datenbericht „Outright Gilt Auctions“",
        "kind": "amtlich",
        "country": "GB",
        "landing": "https://www.dmo.gov.uk/data/gilt-market/auctions-results/",
        "download": "https://www.dmo.gov.uk/data/pdfdatareport?reportCode=D2.1A",
        "manual": True,
        "file": "gb/dmo_outright_gilt_auctions.xls",
        "used_for": "Einzelne Gilt-Auktionen: Datum, Anleihe, Nominalbetrag (Auktion und PAOF), Cash-Erlös, Durchschnittskurs, Rendite. "
                    "Grundlage der britischen Jahrgangskosten ab 1998.",
    },
    "gb_tenders": {
        "title": "Results of Outright Gilt Tenders (ab 2008)",
        "publisher": "UK Debt Management Office (DMO), Datenbericht „Gilt Tenders – Outright Sales“",
        "kind": "amtlich",
        "country": "GB",
        "landing": "https://www.dmo.gov.uk/data/gilt-market/",
        "download": "https://www.dmo.gov.uk/data/pdfdatareport?reportCode=D2.1PROF9",
        "manual": True,
        "file": "gb/dmo_gilt_tenders.xls",
        "used_for": "Einzelne Gilt-Tender mit Valuta, Nominalbetrag, Cash-Erlös, Kurs und Rendite.",
    },
    "gb_other_ops": {
        "title": "Results of other gilt operations (Umtausch, Konversion, Rückkauf, Emission an die DMO)",
        "publisher": "UK Debt Management Office (DMO)",
        "kind": "amtlich",
        "country": "GB",
        "landing": "https://www.dmo.gov.uk/data/gilt-market/",
        "download": "https://www.dmo.gov.uk/data/pdfdatareport?reportCode=D2.1PROF7",
        "manual": True,
        "file": "gb/dmo_other_gilt_operations.xls",
        "used_for": "Abgrenzung: Umtausch- und Konversionsgeschäfte sowie Emissionen direkt an die DMO (Sicherheiten für die "
                    "Kassensteuerung) bringen keine Finanzierungsmittel und werden nicht als Kreditaufnahme gezählt.",
    },
    "gb_syndications": {
        "title": "Syndizierungen 2025–26 (Annual Review, Table 12)",
        "publisher": "UK Debt Management Office (DMO), Gilt Annual Review 2025–26",
        "kind": "amtlich",
        "country": "GB",
        "landing": "https://www.dmo.gov.uk/publications/",
        "download": "https://www.dmo.gov.uk/media/zvypwjss/gar2026.pdf",
        "manual": True,
        "file": "gb/dmo_syndications_2025_26.csv",
        "used_for": "Die sieben Syndizierungen des Haushaltsjahres 2025–26 (Nominal, Emissionskurs, Rendite, Cash-Erlös), aus Table 12 "
                    "abgeschrieben und gegen das PDF geprüft. Syndizierungen früherer Jahre fehlen.",
    },
    "gb_annual_review": {
        "title": "Gilt Annual Review 2025–26",
        "publisher": "UK Debt Management Office (DMO)",
        "kind": "amtlich",
        "country": "GB",
        "landing": "https://www.dmo.gov.uk/publications/",
        "download": "https://www.dmo.gov.uk/media/zvypwjss/gar2026.pdf",
        "file": "gb/dmo_annual_review_2025_26.pdf",
        "used_for": "Prüfwerte: Summen aus Auktionen, PAOF, Syndizierungen und Tendern im Haushaltsjahr 2025–26 (Table 5).",
    },
    "gb_rpi": {
        "title": "RPI All Items Index (Jan 1987 = 100), Reihe CHAW",
        "publisher": "Office for National Statistics (ONS), Datensatz MM23",
        "kind": "amtlich",
        "country": "GB",
        "landing": "https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/chaw/mm23",
        "download": "https://www.ons.gov.uk/generator?format=csv&uri=/economy/inflationandpriceindices/timeseries/chaw/mm23",
        "file": "gb/ons_rpi_chaw.csv",
        "used_for": "Referenz-RPI und Index-Verhältniszahlen der inflationsindexierten Gilts mit 3-Monats-Verzögerung; "
                    "danach Projektion 0/2/4 % p. a.",
    },
    "wb_interest": {
        "title": "World Development Indicators: Interest payments (current LCU), GC.XPN.INTP.CN",
        "publisher": "Weltbank (Datenbasis: IWF Government Finance Statistics)",
        "kind": "international",
        "country": None,
        "landing": "https://data.worldbank.org/indicator/GC.XPN.INTP.CN",
        "download": f"https://api.worldbank.org/v2/country/{WB_COUNTRIES}/indicator/GC.XPN.INTP.CN?format=json&per_page=2000&date=1960:2030",
        "file": "intl/worldbank_GC.XPN.INTP.CN.json",
        "used_for": "Gezahlte Zinsen des Zentralstaats in Landeswährung als Vergleichszahl für Jahre und Länder "
                    "ohne amtliche Einzeldaten. Nicht für Jahrgangskosten verwendbar.",
    },
    "imf_weo": {
        "title": "World Economic Outlook: Finanzierungssaldo, Primärsaldo und Bruttoschulden des Gesamtstaats (% des BIP)",
        "publisher": "Internationaler Währungsfonds (IWF), SDMX-Schnittstelle, Datensatz IMF.RES:WEO",
        "kind": "international",
        "country": None,
        "landing": "https://www.imf.org/en/Publications/WEO",
        "download": "https://api.imf.org/external/sdmx/2.1/data/IMF.RES,WEO,9.0.0/" + "+".join(G20)
                    + ".GGXCNL_NGDP+GGXONLB_NGDP+GGXWDG_NGDP.A?format=csv",
        "accept": "application/vnd.sdmx.data+csv;version=1.0.0",
        "file": "intl/imf_weo_g20.csv",
        "used_for": "Gesamtstaat (alle Ebenen): Nettozinsausgaben = Primärsaldo − Finanzierungssaldo (in % des BIP, abgeleitet) "
                    "und Schuldenstand. Werte nach dem letzten Ist-Jahr sind IWF-Projektionen. Nicht für Jahrgangskosten verwendbar.",
    },
}

# Amtliche Quellen für Einzelemissionen weiterer Länder: erfasst, aber (noch) nicht importiert.
# "check" dokumentiert den Stand der automatischen Abrufprüfung aus dieser Arbeitsumgebung.
CANDIDATES = [
    {"country": "CA", "title": "Bank of Canada – Government of Canada bond and bill auction results",
     "url": "https://www.bankofcanada.ca/markets/government-securities-auctions/", "check": "Valet-API erreichbar, Auktionsreihen nicht geprüft",
     "note": "Import nicht umgesetzt."},
    {"country": "FR", "title": "Agence France Trésor – Résultats des adjudications",
     "url": "https://www.aft.gouv.fr/fr/resultats-adjudications", "check": "automatischer Abruf blockiert (HTTP 403)",
     "note": "Einzelauktionen OAT/BTF; Import nicht umgesetzt."},
    {"country": "IT", "title": "Dipartimento del Tesoro – Risultati delle aste",
     "url": "https://www.dt.mef.gov.it/it/debito_pubblico/emissioni_titoli_di_stato_interni/", "check": "automatischer Abruf blockiert (HTTP 403)",
     "note": "Einzelauktionen BTP/BOT/CCTeu (variabel verzinst); Import nicht umgesetzt."},
    {"country": "AU", "title": "Australian Office of Financial Management – Tender results",
     "url": "https://www.aofm.gov.au/", "check": "automatischer Abruf blockiert (HTTP 403)", "note": "Import nicht umgesetzt."},
    {"country": "JP", "title": "Ministry of Finance Japan – JGB auction results",
     "url": "https://www.mof.go.jp/english/policy/jgbs/auction/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "IN", "title": "Reserve Bank of India – Auction results of government securities",
     "url": "https://www.rbi.org.in/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "BR", "title": "Tesouro Nacional – Resultados dos leilões",
     "url": "https://www.tesourotransparente.gov.br/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "MX", "title": "Banco de México – Subastas de valores gubernamentales",
     "url": "https://www.banxico.org.mx/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "KR", "title": "Ministry of Economy and Finance – KTB auction results",
     "url": "https://ktb.moef.go.kr/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "ZA", "title": "National Treasury – Government bond auction results",
     "url": "https://www.treasury.gov.za/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "TR", "title": "Hazine ve Maliye Bakanlığı – İhale sonuçları",
     "url": "https://www.hmb.gov.tr/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "ID", "title": "Kementerian Keuangan (DJPPR) – Hasil lelang SBN",
     "url": "https://www.djppr.kemenkeu.go.id/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "CN", "title": "Ministry of Finance / ChinaBond – Treasury bond issuance",
     "url": "https://www.chinabond.com.cn/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "AR", "title": "Ministerio de Economía – Licitaciones de títulos públicos",
     "url": "https://www.argentina.gob.ar/economia/finanzas", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "RU", "title": "Ministry of Finance of Russia – OFZ auction results",
     "url": "https://minfin.gov.ru/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
    {"country": "SA", "title": "National Debt Management Center – Sukuk issuance",
     "url": "https://www.ndmc.gov.sa/", "check": "nicht geprüft", "note": "Import nicht umgesetzt."},
]

# Englische Übersetzungen für die Quellenansicht (Titel, Verwendung). Die deutschen Texte oben sind maßgeblich.
SOURCES_EN = {
    "de_emissionshistorie": ("Auction results since 1999 (issuance history)",
                             "Every individual issue: date, ISIN, coupon, maturity, allotted volume, retention/own holdings, weighted average price, average yield. Basis of all values marked “calculated from individual issues”."),
    "de_einzelaufstellung_jahre": ("Outstanding federal securities – list at year-ends since 1995",
                                   "Interest start date per ISIN for accrued interest and first coupon; check of issue volumes against amounts outstanding."),
    "de_einzelaufstellung": ("Outstanding federal securities – current list", "Interest start date of new securities of the current year."),
    "de_schuldenbericht": ("Debt report: debt, gross borrowing, redemptions, interest (monthly since 1995)",
                           "Interest actually paid in the year (comparison figure), official gross borrowing and redemptions (split refinancing/net borrowing, coverage)."),
    "de_referenzindex_2005": ("Archive of daily reference index and index ratios (base year 2005)", "Realised index ratios of inflation-linked federal securities 2006–2016."),
    "de_referenzindex_2015": ("Archive of daily reference index and index ratios (base year 2015)",
                              "Realised index ratios from 2016, base indices, interest start and first coupon of inflation-linked federal securities; starting point of the inflation projection."),
    "de_referenzindex_2025": ("Daily reference index and index ratios (base year 2025)",
                              "Current index ratios after rebasing the HICP to 2025=100; the last official value is the starting point of the inflation projection."),
    "bbk_gross": ("Gross sales of federal bonds at nominal value (monthly from 1948)",
                  "Gross borrowing via federal bonds before 1999 (official, aggregated); net sales from the change in amounts outstanding. From 2000 including Bubills and financing notes."),
    "bbk_gross_le4": ("Gross sales of federal bonds, agreed maturity up to 4 years (monthly from 1960)", "Model of the interest burden 1960–1998: short-term volume."),
    "bbk_gross_gt4": ("Gross sales of federal bonds, agreed maturity over 4 years (monthly from 1960)", "Model of the interest burden 1960–1998: long-term volume."),
    "bbk_em_yield": ("Yields at issue of listed federal securities (monthly from 1960)", "Model of the interest burden 1960–1998: yield of federal securities issued in the month."),
    "bbk_outstanding": ("Federal bonds outstanding at nominal value (monthly from 1948)",
                        "Net sales = change in amount outstanding; refinancing = gross sales − net sales (before 1995)."),
    "bbk_umlaufrendite": ("Yield on listed federal securities outstanding (monthly from 1960)",
                          "Model 1960–1998: substitute yield for months in which volume was issued but no issue yield was published."),
    "bbk_vgr_interest": ("Interest expenditure of general government (national accounts, ESA 2010), annual from 1970",
                         "General government view: interest expenditure of Bund, Länder, municipalities and social security (accrual basis, national accounts)."),
    "us_auctions": ("Treasury Securities Auctions Data (all auctions since 1979)",
                    "Every individual auction of bills, notes, bonds, TIPS and FRNs: price, accrued interest, coupon, maturity, allotted volume. Basis of the US vintage costs."),
    "us_interest_expense": ("Interest Expense on the Public Debt Outstanding (monthly from May 2010)",
                            "Interest paid or accrued on federal debt per calendar year (comparison figure, complete from 2011)."),
    "us_tips_refcpi": ("TIPS: daily reference CPI values (from May 2008)",
                       "Index ratios of TIPS (reference CPI / reference CPI at dated date). Before May 2008: interpolation between official reference CPI values on issue dates (modelled)."),
    "gb_auctions": ("Results of outright gilt auctions (from 1998, including PAOF)",
                    "Individual gilt auctions: date, gilt, nominal amount (auction and PAOF), cash raised, average price, yield. Basis of the UK vintage costs from 1998."),
    "gb_tenders": ("Results of outright gilt tenders (from 2008)",
                   "Individual gilt tenders with settlement date, nominal amount, cash raised, price and yield."),
    "gb_other_ops": ("Results of other gilt operations (switches, conversions, reverse auctions, issuance to the DMO)",
                     "Scope: switches, conversions and issuance directly to the DMO (collateral for cash management) raise no financing and are not counted as borrowing."),
    "gb_syndications": ("Syndications 2025–26 (Annual Review, Table 12)",
                        "The seven syndications of fiscal year 2025–26 (nominal, issue price, yield, cash proceeds), transcribed from Table 12 and checked against the PDF. Syndications of earlier years are missing."),
    "gb_annual_review": ("Gilt Annual Review 2025–26",
                         "Check values: totals from auctions, PAOF, syndications and tenders in fiscal year 2025–26 (Table 5)."),
    "gb_rpi": ("RPI All Items Index (Jan 1987 = 100), series CHAW",
               "Reference RPI and index ratios of index-linked gilts with a 3-month lag; after that projection 0/2/4% p.a."),
    "wb_interest": ("World Development Indicators: Interest payments (current LCU), GC.XPN.INTP.CN",
                    "Interest paid by central government in local currency as a comparison figure for years and countries without official individual data. Not usable for vintage costs."),
    "imf_weo": ("World Economic Outlook: overall balance, primary balance and gross debt of general government (% of GDP)",
                "General government (all levels): net interest = primary balance − overall balance (% of GDP, derived) and debt. Values after the last actual year are IMF projections. Not usable for vintage costs."),
}
